using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo.Encapsulation
{
    internal struct Employee
    {

        #region Attributes

        //public int id;//abuse using Encapsulation
        private int id;
        private string? name;
        private decimal salary;
        private decimal deduction;//derived Attribute [Calculated in run time using salary attribute].

        #endregion

        #region Properties => Apply Encapsulation through Properties. [New Approach]

        #region 1.1 Full Properties [full because I wrote Fields & Properties].

        //propfull => is a code snippet for [full property]

        public int Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        public string? Name
        {
            get
            {
                return this.name;
            }
            init
            {

                //this.name = value?.Length<=10?value:value?.Substring(0,10);
                this.name = NewName(value);
            }
            //init
            //{

            //    //this.name = value?.Length<=10?value:value?.Substring(0,10);
            //    this.name = string.IsNullOrWhiteSpace(value) ? "No Name" : (value.Length <= 10) ? value : value.Substring(0, 10);
            //}

            //init [.NET 5.0 - C#9.0] feature => Allow modification on object attribute through init using object initializer only. [you can write "set" or "init" for one attribute not the two methods] 
        }

        public decimal Salary
        {
            get
            {
                return this.salary;
            }
            set
            {
                this.salary = NewSalary(value);
            }
        }

        //Read only property [not have set method [can't set it by my self]]
        public decimal Deduction
        {
            get { return salary * .2M; }
        }

        #endregion

        #region 1.2 Automatic properties [Automatic because i write the property only and field automatic generated by compiler]

        //prop => is a code snippet for [Automatic property]

        public int Age { get; set; } //When use automatic property, you have not access on field itself, so you will deal with property not attribute inside the struct or class.

        #endregion

        #endregion

        #region Constructors

        public Employee(int id, string? name, decimal salary,int age)
        {
            this.id = id;
            this.name = NewName(name);
            this.salary = NewSalary(salary);
            this.Age/*Age Automatic Property not the attribute*/ = age;
        }

        #endregion

        #region Methods

        #region Setters & Getters.

        #region Apply Encapsulation through Setters & Getters Methods. [Old Approach]
        public void SetId(int id)
        {
            this.id = (id > 1000 & id < 10000) ? id : 9999;
        }
        public int getID() => this.id;

        public void SetName(string? name)
        {
            this.name = name;
        }
        public string? getName() => this.name;

        public void SetSalary(decimal salary)
        {
            this.salary = (salary < 5000) ? 5000 : salary;
        }
        public decimal getSalary() => this.salary;

        public void setAge(int age)
        {
            this.Age/*Automatic Property*/ = age;
        }
        public int getAge() => this.Age/*Automatic Property*/;

        #endregion

        #endregion

        #region Another Methods

        public override string ToString() => $"ID = {this.id}\nName = {this.name}\nSalary = {this.salary:c}\nAge = {this.Age}";

        private string? NewName(string? name)
        {
            return string.IsNullOrWhiteSpace(name) ? "No Name" : name.Length <= 10 ? name : name.Substring(0, 10);
        }

        private decimal NewSalary(decimal salary)
        {
            return salary >= 5000 ? salary : 5000;
        }

        #endregion

        #endregion

    }
}
