using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demo
{
    #region Part 01 Struct

    /*

         * Why Represent Point(dataType) as struct not class ?
         * - Because it consists of (8 Byte) of data only.
     
     */

    internal struct Point
    {

        #region Attributes

        private int x;//x,y => Called ( Fields - Attributes - Member variables ), Must be private(Encapsulation), And convention of naming attributes is pascalCase (ex-> genderAttribute).
        private int y;//Those Attributes are object members from struct, not struct member - We say that members are struct member if there are static members
                      //object members, Mean that any object will created from struct "Point" Will has (x,y); 
        #endregion

        #region Constructors

        /*

             * Constructor is a special function because :
             * - Always named with the same name of struct or class
             * - Not has return type.

             * The access modifier of constructor inside struct must be (nonprivate) -> ( internal | public )
             * The access modifier of constructor inside class may be one of the 6 Access Modifiers, But in real projects it will be (nonprivate).
             * - The constructor inside class can be private if and only if we need to implement singleton design pattern, To prevent multiple instantiation/objects from class - You can only make one object from class

         */

        /*

             * The function of struct constructor is differ from class constructor => 
             * struct constructor -> Responsible for initialization of attributes of struct object [ object attributes initialization ].

             * That's because C#11, If you don't initialize each and every attribute in struct with values using constructor, The compiler will give you Error on constructor declaration.
 
             * Start with c#11, Compiler not give you Error, Because it make the initialization of attributes with the default value of it's type in background.
  
             * Mean that when you write this:

               public Point()
               {

               }

             * The compiler will auto generate this code => 

                public Point()
               {
                  x = default;//0
                  y = default;//0
               }

         */

        #region Default Constructor [Parameterless constructor] [auto generated by compiler]

        //Before (C#10.0) You can't write the parameterless constructor, it's just generated by compiler.
        //public Point() // This is the auto generated constructor by the compiler even if you not write it, Responsible for initialize the struct object attribute with the default value.
        //{
        //    x = default;
        //    y = default;
        //}

        #endregion

        #region Default Constructor [Parameterless constructor] [user defined]
        //start with (C#10.0) You can write the parameterless constructor, and modify the default initialization of compiler to the object attributes.
        public Point() // This is the auto generated constructor by the compiler even if you not write it, Responsible for initialize the struct object attribute with the default value.
        {
            x = 5;//Modify The default initialization of compiler.
            y = 10;
        }

        public Point(int x) : this()
        {
            this.x = x;
        }

        #endregion

        #region Parameterized constructor [override the default value of attributes with the value of parameters passed].

        //When make constructors with same name, different signature (Type - number) of parameters, it's called (constructor overloading). 
        public Point(int x,int y)
        {
            this.x = x;//this refer to the object that we call the constructor to it, and this (x) is the attribute of the object. 
            this.y = y;
        }

        #endregion

        #endregion

        #region Methods

        #region override the default return of ToString() in struct, to let it return the status of the struct object.

        public override string ToString()
        {
            return $"({this.x},{this.y})";//(this) -> refer to the object that call this method.
        }

        #endregion

        #endregion

    }
    #endregion
}
